---
- hosts: webservers
  become: yes
  vars: 
   myvar1: kranthi
   myvar2: kumar
   myvar3: kyatham
  tasks:  
  - name: display myvar1
    debug: 
     msg: "{{myvar1}}"
  - name: display myvar2
    debug:
     msg: "{{myvar2}}"
  - name: display myvar3
    debug: 
     msg: "{{myvar3}}"       