---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu14
    apt:
     name: apache2
     state: present 
  - name: restart the service
    service:
     name: apache2
     state: restarted   

