---
- hosts: all
  become: yes
  tasks:
  - name: install tree,git,wget into nodes
    apt:
     name: git
     state: present
  - name: install tree
    apt:
     name: tree
     state: tree
  - name: install wget
    apt:
     name: tree
     state: present